# Generated by Django 5.2.6 on 2026-09-21 08:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('eggs_collected', models.PositiveIntegerField(default=0)),
                ('broken_eggs', models.PositiveIntegerField(default=0)),
                ('rejected_eggs', models.PositiveIntegerField(default=0)),
                ('trays', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_productions', to='flocks.flock')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
