# Generated by Django 4.2.30 on 2026-09-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='is_egg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('tray', 'Tray')], default='piece', max_length=20),
        ),
    ]
