# Generated by Django 5.2.6 on 2026-09-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=150)),
                ('arrival_date', models.DateField()),
                ('initial_quantity', models.PositiveIntegerField(default=0)),
                ('current_quantity', models.PositiveIntegerField(default=0)),
                ('age_weeks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('closed', 'Closed')], default='active', max_length=20)),
                ('house', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
