# Generated by Django 5.2.6 on 2026-09-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm_name', models.CharField(default='KukuFarm', max_length=200)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('currency', models.CharField(choices=[('TZS', 'TZS - Tanzanian Shilling'), ('USD', 'USD - US Dollar'), ('KES', 'KES - Kenyan Shilling'), ('UGX', 'UGX - Ugandan Shilling')], default='TZS', max_length=10)),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=100)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('mortality_alerts', models.BooleanField(default=True)),
                ('vaccination_alerts', models.BooleanField(default=True)),
                ('production_alerts', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Farm Settings',
                'verbose_name_plural': 'Farm Settings',
                'ordering': ['id'],
            },
        ),
    ]
