# Generated by Django 4.2.30 on 2026-09-29 06:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flocks', '0001_initial'),
        ('feed', '0002_feedpurchase_created_by_alter_feedstock_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('OPENING_STOCK', 'Opening Stock'), ('ADJUSTMENT', 'Adjustment'), ('CONSUMPTION', 'Consumption')], max_length=30)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_stock_movements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='feed',
            name='feed_type',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.DeleteModel(
            name='FeedPurchase',
        ),
        migrations.AddField(
            model_name='feedstockmovement',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='feed.feed'),
        ),
        migrations.AddField(
            model_name='feedstockmovement',
            name='flock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feed_stock_movements', to='flocks.flock'),
        ),
    ]
