# Generated by Django 5.2.6 on 2026-09-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Feed', 'Feed'), ('Medication', 'Medication'), ('Vaccination', 'Vaccination'), ('Veterinary Services', 'Veterinary Services'), ('Utilities', 'Utilities'), ('Electricity', 'Electricity'), ('Water', 'Water'), ('Labour', 'Labour'), ('Transport', 'Transport'), ('Fuel', 'Fuel'), ('Maintenance', 'Maintenance'), ('Equipment', 'Equipment'), ('Farm Supplies', 'Farm Supplies'), ('Cleaning Supplies', 'Cleaning Supplies'), ('Disinfectants', 'Disinfectants'), ('Poultry House Repairs', 'Poultry House Repairs'), ('Farm Construction', 'Farm Construction'), ('Land/Rent', 'Land/Rent'), ('Security', 'Security'), ('Insurance', 'Insurance'), ('Licenses & Permits', 'Licenses & Permits'), ('Communication', 'Communication'), ('Internet', 'Internet'), ('Marketing & Advertising', 'Marketing & Advertising'), ('Packaging', 'Packaging'), ('Egg Trays', 'Egg Trays'), ('Sacks & Bags', 'Sacks & Bags'), ('Stationery', 'Stationery'), ('Office Expenses', 'Office Expenses'), ('Bank Charges', 'Bank Charges'), ('Mobile Money Charges', 'Mobile Money Charges'), ('Professional Services', 'Professional Services'), ('Veterinary Consultation', 'Veterinary Consultation'), ('Waste Management', 'Waste Management'), ('Pest Control', 'Pest Control'), ('Depreciation', 'Depreciation'), ('Loan Interest', 'Loan Interest'), ('Taxes', 'Taxes'), ('Training', 'Training'), ('Miscellaneous', 'Miscellaneous'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
